name: automerge
on:
  issue_comment:
    types: [created]
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/release') && github.event.comment.author_association == 'OWNER'
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run: echo hello
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "Release new version"
          MERGE_FILTER_AUTHOR: "AlexPerathoner"