name: "Create Draft Release"

on:
  issue_comment:
    types: [created]

concurrency: 
  group: publish-release${{ github.ref }}
  cancel-in-progress: true

env:
  projname: testSparkleRelease

jobs:
  check-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        if: contains(github.event.comment.body, '/release')
        env:
          STUFF: ${{ toJson(github.event) }}
        run: echo "$STUFF"